<?php


$blocks = array_map(function($block){ return $block->jsonSerialize();}, $this->options->getBlocks());


?>
<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    #gjs {
        border: 3px solid #444;
    }
</style>

<div id="gjs" style="height:0; overflow:hidden;">
    hello
</div>
<div id="blocks"></div>
<script type="text/javascript">
    const editor = grapesjs.init({
        // Indicate where to init the editor. You can also pass an HTMLElement
        container: '#gjs',
        // Get the content for the canvas directly from the element
        // As an alternative we could use: `components: '<h1>Hello World Component!</h1>'`,
        fromElement: true,
        // Size of the editor
        height: '100vh',
        width: '100vw',
        // Disable the storage manager for the moment
        storageManager: {
            id: 'gjs-',             // Prefix identifier that will be used on parameters
            type: 'remote',          // Type of the storage
            autosave: true,         // Store data automatically
            autoload: true,         // Autoload stored data on init
            stepsBeforeSave: 1,     // If autosave enabled, indicates how many changes are necessary before store method is triggered
            urlStore: 'http://endpoint/store-template/some-id-123',
            urlLoad: 'http://endpoint/load-template/some-id-123',
        },
        assetManager: {
            assets: [
                'http://placehold.it/350x250/78c5d6/fff/image1.jpg',
                // Pass an object with your properties
                {
                    type: 'image',
                    src: 'http://placehold.it/350x250/459ba8/fff/image2.jpg',
                    height: 350,
                    width: 250,
                    name: 'displayName'
                },
                {
                    // As the 'image' is the base type of assets, omitting it will
                    // be set as `image` by default
                    src: 'http://placehold.it/350x250/79c267/fff/image3.jpg',
                    height: 350,
                    width: 250,
                    name: 'displayName'
                },
            ],
            noAssets: '',
             upload: 0,
            // uploadName: 'files',
            // headers: {},
            // params: {},
            // credentials: 'include',
            // multiUpload: true,
             autoAdd: 1,
            // uploadText: 'Drop files here or click to upload',
            // addBtnText: 'Add image',
            // uploadFile: '',
            // handleAdd: '',
             dropzone: 1,
            openAssetsOnDrop: 0,
            dropzoneContent: '',
                modalTitle: 'Select Image',
        },
        // Avoid any default panel
        plugins: [
            'grapesjs-parser-postcss',
            'gjs-preset-<?=  $this->layout()->type ?>'
        ],
        pluginsOpts: {
            'gjs-preset-newsletter': {
                modalLabelImport: 'Paste all your code here below and click import',
                modalLabelExport: 'Copy the code and use it wherever you want',
                codeViewerTheme: 'material',
                //defaultTemplate: templateImport,
                importPlaceholder: '',
                cellStyle: {
                    'font-size': '12px',
                    'font-weight': 300,
                    'vertical-align': 'top',
                    color: 'rgb(111, 119, 125)',
                    margin: 0,
                    padding: 0,
                }
            }
        },
       
    });

    <?php foreach($this->options->getBlocks() as $block){ ?>
        editor.BlockManager.add('<?= $block->getId() ?>', <?= $block->jsonSerialize() ?>);
    <?php } ?>
    
</script>
