
<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$grapejsCss = 'https://unpkg.com/grapesjs-preset-newsletter@0.2.20/dist/grapesjs-preset-newsletter.css';
$grapejsPreset = 'https://unpkg.com/grapesjs-preset-newsletter@0.2.20/dist/grapesjs-preset-newsletter.min.js';
if( $this->type == 'webpage'){
    $grapejsCss = 'https://unpkg.com/grapesjs-preset-webpage@0.1.11/dist/grapesjs-preset-webpage.min.css';
    $grapejsPreset = 'https://unpkg.com/grapesjs-preset-webpage@0.1.11/dist/grapesjs-preset-webpage.min.js';
}


?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>
    
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($grapejsCss)
        ->prependStylesheet('//unpkg.com/grapesjs@0.14.57/dist/css/grapes.min.css')
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($grapejsPreset)
        ->prependFile('https://unpkg.com/grapesjs-parser-postcss')
        ->prependFile('//unpkg.com/grapesjs@0.14.57/dist/grapes.min.js') ?>
    
</head>
<body>
<div class="">
    <?= $this->content ?>
</div>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>
